[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "NODE_ENV=production npm run build"]

[start]
cmd = "bash start.sh"
